// <auto-generated />
using System;
using CursosYViajes;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CursosYViajes.Datos.Migrations
{
    [DbContext(typeof(ContextoCursoYViajes))]
    partial class ContextoCursoYViajesModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CursosYViajes.Alumno", b =>
                {
                    b.Property<Guid>("IdAlumno")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("IdAlumno");

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("CursosYViajes.Curso", b =>
                {
                    b.Property<Guid>("IdCurso")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("IdPais");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("IdCurso");

                    b.HasIndex("IdPais");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("CursosYViajes.CursoPorAlumno", b =>
                {
                    b.Property<Guid>("IdCursoPorAlumno")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("IdAlumno");

                    b.Property<Guid>("IdCurso");

                    b.HasKey("IdCursoPorAlumno");

                    b.HasIndex("IdAlumno");

                    b.HasIndex("IdCurso");

                    b.ToTable("CursosPorAlumno");
                });

            modelBuilder.Entity("CursosYViajes.Pais", b =>
                {
                    b.Property<Guid>("IdPais")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("IdPais");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("CursosYViajes.Curso", b =>
                {
                    b.HasOne("CursosYViajes.Pais", "Pais")
                        .WithMany("Cursos")
                        .HasForeignKey("IdPais")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CursosYViajes.CursoPorAlumno", b =>
                {
                    b.HasOne("CursosYViajes.Alumno", "Alumno")
                        .WithMany("CursosPorAlumno")
                        .HasForeignKey("IdAlumno")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CursosYViajes.Curso", "Curso")
                        .WithMany("AlumnosPorCurso")
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
